### ISSUE TITLE
VCV Rack Free v2.0.3 - Random Wrangler crashing

### ISSUE THREAD

**Issue by firolightfog** [thomassidor/tinytricks#24]
I wanted to select Random Wrangler (RW) in the Rack plugin browser but it crashed. I use v2.0.3 under Win10. 

The last few lines of the log.txt look like this:
`C:/Users/aszabo/Documents/Rack2/plugins/CountModula/res/G2T.svg
[8.347 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/components/PortLight.svg
[8.347 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/RoundSmallBlackKnob.svg
[8.348 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/RoundSmallBlackKnob_bg.svg
[8.349 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTTRI.svg
[8.350 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/ScrewBlack.svg
[8.358 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/RW.svg
[8.358 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/LargeLight.svg
[8.359 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSQRPLUS.svg
[8.359 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTA.svg
[8.360 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSIN.svg
[8.360 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/A8.svg
[8.361 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSQR.svg
[8.361 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/RX8.svg
[8.362 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/RM8S.svg
[8.363 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSAWPLUS.svg
[8.394 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/LFO8.svg
[8.395 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSINPLUS.svg
[8.396 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTTRIPLUS.svg
[8.396 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/LFO16.svg
[8.397 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/SH16.svg
[8.425 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/TTSAW.svg
[8.425 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/LFO1.svg
[8.426 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/components/Wavetable.svg
[8.426 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/CKSSThree_0.svg
[8.426 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/CKSSThree_1.svg
[8.427 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/OneDrive - UNICEF/private/DAW/Rack2Free/res/ComponentLibrary/CKSSThree_2.svg
[8.428 info src/window/Svg.cpp:28 loadFile] Loaded SVG C:/Users/aszabo/Documents/Rack2/plugins/TinyTricks/res/panels/WAVE.svg
[10.240 fatal adapters/standalone.cpp:60 fatalSignalHandler] Fatal signal 22 SIG. Stack trace:
36:  0x0
35: raise 0x7fffc100ac60
34: abort 0x7fffc100f270
33: ZN9TTLWidgetD1Ev 0xcae8f0
32: ZN10WAVEWidgetD1Ev 0xc7ecf0
31: ZSt7shuffleIN9__gnu_cxx17__normal_iteratorIPiSt6vectorIiSaIiEEEERSt26linear_congruential_engineIjLj16807ELj0ELj2147483647EEEvT_SA_OT0_ 0xd3f980
30: ZZN4rack11createModelI9RM8Stereo15RM8StereoWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModelD1Ev 0xd4e000
29: ZZN4rack11createModelI9RM8Stereo15RM8StereoWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModelD1Ev 0xd4e000
28: ZNSt6vectorIiSaIiEE17_M_realloc_insertIJiEEEvN9__gnu_cxx17__normal_iteratorIPiS1_EEDpOT_ 0xd2e5f0
27: ZN14RANDOMWRANGLERC1Ev 0xc8ada0
26: ZZN4rack11createModelI14RANDOMWRANGLER20RANDOMWRANGLERWidgetEEPNS_6plugin5ModelENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModel12createModuleEv 0xd46a40
25: ZN4rack3app11AudioButton8onActionERKNS_6widget6Widget11ActionEventE 0x7fff48faca30
24: ZN4rack3app7browser8ModelBox8onButtonERKNS_6widget6Widget11ButtonEventE 0x7fff4944b390
23: ZN4rack6widget6Widget8onButtonERKNS1_11ButtonEventE 0x7fff49471d70
22: ZN4rack6widget6Widget8onButtonERKNS1_11ButtonEventE 0x7fff49471d70
21: ZN4rack6widget6Widget8onButtonERKNS1_11ButtonEventE 0x7fff49471d70
20: ZN4rack2ui12ScrollWidget8onButtonERKNS_6widget6Widget11ButtonEventE 0x7fff48fed900
19: ZN4rack3app7browser7Browser8onButtonERKNS_6widget6Widget11ButtonEventE 0x7fff49449290
18: ZN4rack2ui11MenuOverlay8onButtonERKNS_6widget6Widget11ButtonEventE 0x7fff48fec8e0
17: ZN4rack6widget12OpaqueWidget8onButtonERKNS0_6Widget11ButtonEventE 0x7fff49471080
16: ZN4rack6widget10EventState12handleButtonENS_4math3VecEiii 0x7fff48ff1b30
15: ZN4rack6window3Svg4loadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x7fff48ff6bc0
14: glfwPlatformUnlockMutex 0x7fff49033f20
13: CallWindowProcW 0x7fffc18f5850
12: CallWindowProcW 0x7fffc18f5850
11: glPushClientAttrib 0x7fff88a53770
10: CallWindowProcW 0x7fffc18f5850
9: DispatchMessageW 0x7fffc18f5410
8: glfwPlatformPollEvents 0x7fff49037920
7: ZN4rack6window6Window4stepEv 0x7fff48ff7f00
6: ZN4rack6window6Window3runEv 0x7fff48ff88c0
5: ZN4rack6window6Window3runEv 0x7fff48ff88c0
4: ZN4rack6window6Window3runEv 0x7fff48ff88c0
3: ZN4rack6window6Window3runEv 0x7fff48ff88c0
2: ZN4rack6window6Window3runEv 0x7fff48ff88c0
1: BaseThreadInitThunk 0x7fffc1ba7c10
0: RtlUserThreadStart 0x7fffc2fad700
`
(Other modules like SH16, SN-OSC, A8 work all fine for me.)

**Comment by firolightfog** [comment]
I used this: [TinyTricks-2.5.0-win.vcvplugin](https://cornwarning.com/xfer/TinyTricks-2.5.0-win.vcvplugin)

**Comment by firolightfog** [comment]
Issue recreated and confirmed as seen in the [topic](https://community.vcvrack.com/t/tinytricks-rw-crashes-vcv2/15516/2) of VCV Forum.

**Comment by cschol** [comment]
Here is the proper backtrace from an unstripped plugin build:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f016cdc5859 in __GI_abort () at abort.c:79
#2  0x0000000000403dc5 in  ()
#3  0x00007f016cde6210 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#5  0x00007f016cdc5859 in __GI_abort () at abort.c:79
#6  0x00007f016d3a6912 in  () at ./libRack.so
#7  0x00007f016d8cf2d6 in __cxxabiv1::__terminate(void (*)()) () at ./libRack.so
#8  0x00007f016d8cf341 in  () at ./libRack.so
#9  0x00007f016d8cf494 in  () at ./libRack.so
#10 0x00007f016d3a7f72 in std::__throw_length_error(char const*) () at ./libRack.so
#11 0x00007f016d94364c in  () at ./libRack.so
#12 0x00007f013f5cfee2 in RANDOMWRANGLER::RANDOMWRANGLER() () at /home/cschol/.Rack2/plugins/TinyTricks/plugin.so
#13 0x00007f013f5d03bc in rack::createModel<RANDOMWRANGLER, RANDOMWRANGLERWidget>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)::TModel::createModule() () at /home/cschol/.Rack2/plugins/TinyTricks/plugin.so
#14 0x00007f016d494eff in  () at ./libRack.so
#15 0x00007f016d49ccb0 in rack::app::browser::ModelBox::onButton(rack::widget::Widget::ButtonEvent const&) () at ./libRack.so
```

The problem is here:
```
82      configParam(RANDOMWRANGLER::LIN_SMOOTH_PARAM, 0.0f, 1.0f, 1.0f, "Smooth shape", {"Exponential", "Linear"});
```

`configParams` expects a single `string` not a list of strings (`{"Exponential", "Linear"}`).

**Comment by firolightfog** [comment]
Just a note: the issue is still open under VCV Rack 2.0.6

**Comment by firolightfog** [comment]
Still crashing in VCV Rack Free 2.1.2 

This seems to be related to _RW duplicate crash #31_
